spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:maindb
    username: sa
    password: password
  liquibase:
    enabled: true
    change-log: classpath:db/migrations/db.changelog-root.xml
    default-schema: public
  server:
    profiles:
      active: test, hsqldb

server:
  port: 8081
springdoc:
  api-docs:
    path: /api-docs

my:
  category:
    Juguetes: 20
    Libros: 15
    Deportes: 5
    Comida: 25
    Ropa: 35
    Otros: 0

logging:
  level:
    org.springframework.web: "DEBUG"
    org.hibernate: "WARN"
    tomcat: "DEBUG"
