spring:
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
server:
  port: 8081
springdoc:
  api-docs:
    path: /api-docs
variables:
  category:
    - {name: Juguetes, discount: 20}
    - {name: Libros, discount: 15}
    - {name: Deportes, discount: 5}
    - {name: Comida, discount: 25}
    - {name: Ropa, discount: 35}
    - {name: Otros, discount: 0}