spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:maindb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    profiles:
      active: test, hsqldb

server:
  port: 8081
  error:
    include-stacktrace: never
springdoc:
  api-docs:
    path: /api-docs

static-table:
  categories:
    Juguetes: 20
    Libros: 15
    Deportes: 5
    Comida: 25
    Ropa: 35
    Otros: 0

services-url:
  cart-url: "http://localhost:8080"
  user-url: "http://localhost:8082"


logging:
  level:
    org.springframework.web: "DEBUG"
    org.hibernate: "WARN"
    tomcat: "DEBUG"
